from socket import socket, AF_INET, SOCK_STREAM # IMPORT DAS BIBLIOTECAS USADAS PARA O TCP/IP
from sys import argv # IMPORT DA TABELA DE ARGUMENTO DO ARQUIVO

HOST = "things.ubidots.com" # HOST PADRÃO DA UBIDOTS
PORT = 9012 # PORTA PADRÃO PARA ESSE TIPO DE CONEXÃO
DEVICE_LABEL = "prueba" # DEVICE LABEL DA UBIDOTS
DEVICE_NAME = "prueba" # DEVICE NAME DA UBIDOTS
TOKEN = "BBUS-TZVDszklDPkg3OxEVDd20V9GbiBMjp" # SECRET_TOKEN OBTIDO NA ABA DEVICES APÓS CRIAR O MESMO
USER_AGENT = "PYTHON/3.0" # USER_AGENT PADRÃO DO PYTHON 3
VARIABLE_LABEL = "bipe" # VARIABLE LABEL OBTIDO NA ABA DEVICES APÓS CRIAR A VARIÁVEL
VALOR = argv[1] # VALOR 0/1 PARA INTERAGIR COM A INTERFACE

msg = f"{USER_AGENT}|POST|{TOKEN}|{DEVICE_LABEL}=>[{VARIABLE_LABEL}:{VALOR}|end" # ENVIO DA MENSAGEM PARA A INTERAÇÃO

cnx = socket(AF_INET, SOCK_STREAM) # ENVIO DA CONEXÃO DA UBIDOTS
cnx.connect((HOST, PORT)) # ENVIO DA CONEXÃO DA UBIDOTS
cnx.sendall(msg.encode()) # ENVIO DA CONEXÃO DA UBIDOTS

print(cnx.recv(10).decode()) # RETORNO DA CONEXÃO